name: Fetching Data
on:
  push:
  schedule:
    - cron: "00 05 * * *"
jobs:
  Fetch-Bus-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch data
        run: |
          python trans_bus_kmb.py
      - name: Update data files
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              routeList.kmb.json
              stopList.kmb.json
            
            commit-msg: Update resources
            github-token: ${{ secrets.ACCESS_TOKEN }}
            branch: main
